# Generated by Django 2.2.12 on 2020-12-06 13:35

from django.db import migrations, models
import file_upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=20)),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
                ('content', models.FileField(upload_to=file_upload.models.user_directory_path)),
                ('language', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
    ]
