# Generated by Django 3.1.2 on 2020-10-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=20)),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
                ('content', models.FileField(upload_to='', verbose_name='/documents/personal/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>')),
                ('language', models.CharField(max_length=20)),
            ],
        ),
    ]
