# Generated by Django 3.1.2 on 2020-10-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_auto_20201022_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_file',
            name='content',
            field=models.FileField(upload_to='documents/personal/eon/<django.db.models.fields.CharField>'),
        ),
    ]
