# Generated by Django 3.1.2 on 2020-10-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0004_auto_20201022_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_file',
            name='content',
            field=models.FileField(upload_to='documents/personal/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>'),
        ),
    ]
