# Generated by Django 3.1.2 on 2020-10-21 22:36

from django.db import migrations, models
import file_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0006_auto_20201022_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_file',
            name='content',
            field=models.FileField(upload_to=file_upload.models.user_directory_path),
        ),
    ]
