# Generated by Django 3.1.2 on 2020-12-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='symlink',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
