# Generated by Django 2.2.12 on 2020-12-02 16:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='refer_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
